# -*- coding: utf-8 -*-
"""Test_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQ7ahrF5AY3V6UkxdRl1aegn1-3eHq03

# Arquitecturas Digitales y RISC
# Introducción a Collaboratory 
## Usando Jupyter para crear *Notebooks*



<img style="float: right; padding-right: 10px; width: 140px" src=" http://drive.google.com/uc?export=view&id=1pxsPAJK5etYYZz0lg5GBhbWO8Veyte_v">
<img style="float: right; padding-right: 10px; width: 140px" src="http://drive.google.com/uc?export=view&id=1GC-aPjsLpinikZNjZlGocVgUw_OO3OWJ">

**Universidad del Valle** <br>
**Escuela de Ingeniería Eléctrica y Electrónica** <br> 
**Estudiante:** Juan  Pablo Zapata Ocampo <br>
"""

# importa la librería de programación numérica rápida y le asigna el nombre
# corto "np" como referencia rápida
import numpy as np
def Saludo_Kevin():
  print("Hola mi nombre es Kevin y soy estudiante de Bionano!")
def Saludo_Karol():
  print("Inserte Aquí Texto Karol")
def Saludo_Harold():
  print("Inserte Aquí Texto Harold")
def Saludo_Juan():
  print("Hola soy Juan")
def Saludo_Jaime():
  print("Inserte Aquí Texto Jaime")
Saludo_Kevin()
Saludo_Karol()
Saludo_Harold()
Saludo_Juan()
Saludo_Jaime()

# se calcula el valor promedio de los elementos del vector
np.mean([1.2, 2, 3.3])
